### Tuples
- Read only list

In [ ]:
# empty tuple
point = ()
point = (1,2) # 1, 2 # 1,

In [5]:
point = (1,2) + (3,4)

point = (1,2) * (3)
print(point)

(1, 2, 1, 2, 1, 2)


In [8]:
nums = [10,20,30]

name = tuple("Ritik")
print(name)

('R', 'i', 't', 'i', 'k')


In [11]:
point = (1,2,3)

print(point[2])

print(point[0:2])

3
(1, 2)


### Swapping Variables

In [12]:
x, y = 4, 8

temp = x
x = y
y = temp

print(x,y)

8 4


In [14]:
x, y = y, x

print("x", x, "y",y)

x 8 y 4


In [17]:
def xorOfTwoValue(x, n, nums=[1,16,8]):
    counter = 0
    move = 0
    for i in range(n):
        for j in range(n):
            result = nums[i] ^ nums[j]
            if result == x:
                print(nums[i], nums[j])
                break
            else:
                if move == 0:
                    maximum = max(nums)
                    move += 1
                maximum //= 2
                nums.append(maximum)
                nums.append(maximum)
                # print(nums)
                break
            
    print(nums)
        # break
    return counter
        

# nums = [8,8,8]
x = 5
n = len(nums)
xorOfTwoValue(x, n)

[1, 16, 8, 8, 8, 4, 4, 2, 2]


0

### Test

In [7]:
# Question 27 Solution
def grade_counter(grades):
    grades_count = {}
    for grade in grades:
        if grade in grades_count:
            grades_count[grade] += 1
        else:
            grades_count[grade] = 1
    return grades_count

grades = [100,95,65,95,65,100,45,65]
print(grade_counter(grades))

{100: 2, 95: 2, 65: 3, 45: 1}


In [21]:
# Question 28: 

import numpy as np

a = (3,6)
print(np.zeros(a))

print(np.arange(-3,21,2))


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[-3 -1  1  3  5  7  9 11 13 15 17 19]


In [13]:
# Question 28: 
# 2
import numpy as np


array([-3, -1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [14]:
# Question 21
a = "Toyota"
print(a[2:3])
print(a[1:4])
print(a[3:])

y
oyo
ota


In [15]:
# Question 22
a = [1,3,5,7]
b = [4,5,7,8,9]
print(a+b)

[1, 3, 5, 7, 4, 5, 7, 8, 9]


In [20]:
forecast = "It will be sunny day today"
# Nof Occurrencess of string 'day' in forecast
print(forecast.count("day"))

print(forecast.capitalize())

print(forecast.replace("sunny","cloudy"))

print(forecast.split(" "))


2
It will be sunny day today
It will be cloudy day today
['It', 'will', 'be', 'sunny', 'day', 'today']


In [26]:
odd = [i for i in range(1,20,2)]
len(odd)
sum(odd)

100

In [34]:
string = "abcd"
string[-1:3]

print (r"\nhello")

print('new' 'line')

print('x\97\x98')

print(0xAC + 0xB + 0xC)



\nhello
newline
x\97˜
195


In [49]:
['f','t'][bool('spam')]

2 + 4.00, 2**4.0

x = -122
print("-%06d"%x)

int(1018)

--00122


1018

In [63]:
a = [0,1,2,3]
for a[0] in a:
    print(a[0])

0
1
2
3


In [62]:
a = [0,1,2,3]
for a[-1] in a:
    print(a[-1])

0
1
2
2


In [70]:
print('ab'.zfill(5))

'my_string'.isidentifier()

string[:-2]

'cccddg'.find('c')

'abcd'.translate('a'.maketrans('abc', 'bcd'))

print("Hello {1} {0}".format("Google", "wala"))



print("abc cdf".title())

000ab
Hello wala Google
Abc Cdf


In [81]:
l1 = [10,20,30]
l2 = [-10,-20,-30]

[x+y for x,y in zip(l1,l2)]

"Apple" is "Apple"
[1,2,3] is [1,2,3]


a = [1,2,3]
b = [4,5,6]
[x*y for y in b for x in a]

a = {1,2,3}
b = a
b.remove(3)
a

sum([5,6,6],5)

a = (1,2)
b = (1,2)

a+b

name = {'name':"Ritik", 'age':22}
name.popitem( )

('age', 22)